# Generated by Django 4.2.6 on 2023-10-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercnpj',
            name='email',
            field=models.EmailField(default='tomanocu@gmail.com', max_length=254),
        ),
    ]
