# Generated by Django 4.2.6 on 2023-11-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usercnpj_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercnpj',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
